### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#19]
How to upgrade from version 0.6.2 to 0.6.3 without losing data?

**Comment by billchen198318** [comment]
Download upgrade bbcore ZIP file:
[bbcore_upgrade.zip](https://github.com/billchen198318/bamboobsc/files/240440/bbcore_upgrade.zip)

1. backup old database bbcore 0.6.2 version. ( Please check whether it is successful dump, In order to avoid a failed upgrade cannot be undone )
># mysqldump bbcore --hex-blob -u root -p > bbcore_062_old.sql

2. upgrade database bbcore to 0.6.3 version.
># mysql bbcore -u root -p < bbcore_062_upgrade_063.sql

3. try to start bambooBSC 0.6.3

 I tested  works OK, But if that fails, please down back to version 0.6.2.

**Comment by giacomozzi** [comment]
Great! Have worked!
