### ISSUE TITLE
KPI ranges 

### ISSUE THREAD

**Issue by maltourky** [billchen198318/bamboobsc#29]
Hello,

how can i make different ranges for each KPI, for example if i want for KPI1 the green color when the result above 90% while for KPI2 the green color when the result above 70%.

another issue, what the effect  when i choose compare with target and compare with minimum in the score calculation and also the maximum and minimum values.

**Comment by billchen198318** [comment]
now only one Color settings, no way do it. 
but you can modify expression ( BSC_RPT_EXPR0005 ) force change KPIs color on Report ( vision, Perspective,Objective cannot force change color).

view the example:
modify expression ( BSC_RPT_EXPR0005 )
![0002](https://cloud.githubusercontent.com/assets/11564867/17836733/5a06c95c-67cf-11e6-9338-e15747dbe00c.png)

change result
![002](https://cloud.githubusercontent.com/assets/11564867/17836734/5c7bf1a8-67cf-11e6-9f2c-a10d151c0e42.png)

compare with target or with minimum will effect the status icon on BSC/KPI-Report.

you can custom the expression change the effect

please view the issues : 

https://github.com/billchen198318/bamboobsc/issues/23

**Warning : if you want modify/update expression , please first backup you database. because the wrong expression bambooBSC system will crash.**
