### ISSUE TITLE
How to integrage measure data?

### ISSUE THREAD

**Issue by flaviocordova** [billchen198318/bamboobsc#31]
Hi..

I have some other tools with data that I'd like to use to feed KPIs data in bamboobsc. I could both enable some kind of API, so bamboobsc could call them go pull the data, or I could create some scripts to push them into bamboobsc using its API.

I couldn't find anything that could give me a clue of what path to take. It looks like creating a new WebService could be the answer, although I'm not sure which classes I'd have to use to write measure data.

Could you give me some guidelines ? :)

**Comment by billchen198318** [comment]
In fact, publishing service become as a webService not problem.

But I  not understand that you only need  measure-data or both need KPI data need.

But bambooBSC KPI data structure not equals you tools KPI data structure. Very different.
it need Vision, Strategy-Object, formula, employee, organization, aggregation method data, ... etc

Even publishing KPI as a webService, The problem is you must do the information to be converted into bambooBSC can accept data, need you self do it.

Enable measure-data create webService step:

1. use Eclipse fetch bambooBSC project code on this repo.

2. remove remark code line for KpiWebService.java and KpiWebServiceImpl.java , to enable the two method: createKpi & measureDataSaveOrUpdate

3. run gsbsc-web project with Eclipse.

browser open webService info page
http://127.0.0.1:8080/gsbsc-web/services/
![0001](https://cloud.githubusercontent.com/assets/11564867/17955169/c6a83344-6ab2-11e6-9690-b00d35c960a7.png)


Test create measure data example
![0002](https://cloud.githubusercontent.com/assets/11564867/17955182/df170270-6ab2-11e6-88f0-b298f695183a.png)

Bye.
