### ISSUE TITLE
update permission (BSC_PROG002D0004E) for 04 - KPI  not working

### ISSUE THREAD

**Issue by abdelazizelesh** [billchen198318/bamboobsc#60]
i added BSC_PROG002D0004E to a new role, when i click save, no permission message raised.
when i added BSC_PROG002D0003E, save done successfully.
![image](https://user-images.githubusercontent.com/6819385/39193805-62079488-47ed-11e8-933c-c80d7163271f.png)

Thanks

**Comment by billchen198318** [comment]
You maybe no to do Role's permitted settings, recommed use Role copy as new. and modify this new role.
because need add many permitted item.

https://github.com/billchen198318/bamboobsc/blob/master/core-doc/dev-docs/06-RoleAndAuthoritySettings.md

the authority has for Controller and for LogicService
@ControllerMethodAuthority for Controller

https://github.com/billchen198318/bamboobsc/blob/master/core-doc/dev-docs/04-ControllerAction.md#basejsonaction ( view Controller annotation  )


@ServiceMethodAuthority for LogicService

https://github.com/billchen198318/bamboobsc/blob/master/core-doc/dev-docs/03-LogicService.md#logic-service-authority-annotation

https://github.com/billchen198318/bamboobsc/blob/master/core-doc/dev-docs/03-LogicService.md#add-logic-service-authority
